# I really only want to remove these once.
# If the user reinstalls them, that's their choice.
# The easiest test is whether anything else I installed is installed.
if (!(Get-Command peazip -ErrorAction Ignore)) {
    Write-Host "=== Uninstall some bloatward that comes with Windows out of the box ===" -ForegroundColor "Yellow"
    @(
        "*.AdobePhotoshopExpress"
        "*.Duolingo-LearnLanguagesforFree"
        "*.EclipseManager"
        "*Autodesk*"
        "*BubbleWitch*"
        "*Facebook*"
        "*Keeper*"
        "*MarchofEmpires*"
        "*Minecraft*"
        "*Netflix*"
        "*Solitaire*"
        "*Twitter*"
        "ActiproSoftwareLLC.562882FEEB491" # Code Writer
        "Microsoft.3DBuilder"
        "Microsoft.BingFinance"
        "Microsoft.BingFinance"
        "Microsoft.BingNews"
        "Microsoft.BingSports"
        "Microsoft.BingWeather"
        "Microsoft.CommsPhone"
        "Microsoft.FreshPaint"
        "Microsoft.GetHelp"
        "Microsoft.Getstarted"
        "Microsoft.Messaging"
        "Microsoft.MicrosoftOfficeHub"
        "Microsoft.MicrosoftStickyNotes"
        "Microsoft.NetworkSpeedTest"
        "Microsoft.Office.Sway"
        "Microsoft.OneConnect"
        "Microsoft.Print3D"
        "Microsoft.WindowsMaps"
        "Microsoft.WindowsPhone"
        "Microsoft.WindowsSoundRecorder"
        "Microsoft.XboxApp"
        "Microsoft.XboxIdentityProvider"
        "Microsoft.ZuneMusic"
        "Microsoft.ZuneVideo"
        "Microsoft.BingNews"
        "Microsoft.GamingApp"
        "Microsoft.Microsoft3DViewer"
        "Microsoft.MSPaint"
        "Microsoft.Paint"
        "Microsoft.People"
        "Microsoft.ScreenSketch"
        "Microsoft.SkypeApp"
        "Microsoft.VP9VideoExtensions"
        # "Clipchamp.Clipchamp"
        # "Microsoft.DesktopAppInstaller"
        # "Microsoft.Office.OneNote"
        # "Microsoft.PowerAutomateDesktop"
        # "Microsoft.WindowsNotepad"
        # "Microsoft.Wallet"
        # "Microsoft.549981C3F5F10" # Cortana
        # "Microsoft.HEIFImageExtension"
        # "Microsoft.Microsoft3DViewer"
        # "Microsoft.MicrosoftEdge.Beta"
        # "Microsoft.MicrosoftEdge.Dev"
        # "Microsoft.MicrosoftEdge.Stable"
        # "Microsoft.MixedReality.Portal"
        # "Microsoft.RawImageExtension"
        # "Microsoft.SecHealthUI"
        # "Microsoft.StorePurchaseApp"
        # "Microsoft.Todos"
        # "Microsoft.WebMediaExtensions"
        # "Microsoft.WebpImageExtension"
        # "Microsoft.Windows.Photos"
        # "Microsoft.WindowsAlarms"
        # "Microsoft.WindowsCalculator"
        # "Microsoft.WindowsCamera"
        # "microsoft.windowscommunicationsapps"
        # "Microsoft.WindowsFeedbackHub"
        # "Microsoft.WindowsStore"
        # "Microsoft.WindowsTerminal"
        # "Microsoft.Xbox.TCUI"
        # "Microsoft.XboxGameOverlay"
        # "Microsoft.XboxGamingOverlay"
        # "Microsoft.XboxSpeechToTextOverlay"
        # "Microsoft.YourPhone"
        # "MicrosoftCorporationII.QuickAssist"
        # "MicrosoftWindows.Client.WebExperience"
    ) | RemoveAppX
}
